### ISSUE TITLE
兄弟，登录不了咯

### ISSUE THREAD

**Issue by 136329859** [ShaoGongBra/xsyx-shop#1]
兄弟，登录不了咯

**Comment by ShaoGongBra** [comment]
能登陆的，你是怎么登陆不上

**Comment by 136329859** [comment]
> 能登陆的，你是怎么登陆不上
用手机号和user-key都不行了，进不了主界面

**Comment by ShaoGongBra** [comment]
我刚刚都还试了用手机号和key都能登陆呀，我的朋友都能登陆上呀，你是不是网络不太好

**Comment by 136329859** [comment]
> 我刚刚都还试了用手机号和key都能登陆呀，我的朋友都能登陆上呀，你是不是网络不太好

![image](https://user-images.githubusercontent.com/7037660/102502576-c13c1600-40b9-11eb-9369-b44fbe30fe85.png)
真的不行，我用的是mac，下载的是github的release的最新安装包

**Comment by ShaoGongBra** [comment]
你是mac卡在登陆界面？能获取到验证码吗

**Comment by 136329859** [comment]
> 你是mac卡在登陆界面？能获取到验证码吗

输入手机可以收到验证码，输验证码之后就出现如上图的报错了

**Comment by ShaoGongBra** [comment]
你这个图片我显示不出来

**Comment by 136329859** [comment]
> 你这个图片我显示不出来

提示，用户信息失效

**Comment by 136329859** [comment]
> 你这个图片我显示不出来

我跟踪代码，可以获取到用户信息，估计是获取不到定位，没有具体的店铺ID，打不开店铺？

**Comment by ShaoGongBra** [comment]
把你的key发给我试试

**Comment by 136329859** [comment]
> 把你的key发给我试试

49125fe0-d5e0-402d-95cb-78ab0e8058bf

**Comment by 136329859** [comment]
> > 把你的key发给我试试
> 
> 49125fe0-d5e0-402d-95cb-78ab0e8058bf

我想问问，大概key多久变一次的？

**Comment by ShaoGongBra** [comment]
新用户没有门店是会有这个问题，这个修复了，明天会发布一个版本

**Comment by 136329859** [comment]
> 新用户没有门店是会有这个问题，这个修复了，明天会发布一个版本

收到！我想问问，大概key多久变一次的？

**Comment by ShaoGongBra** [comment]
现在好像改规则了，暂时不清楚，之前是只支持一个端登陆，在其他端登陆一下key就会失效

**Comment by ShaoGongBra** [comment]
新版本已经发布了
